// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC60WCUTl6IgD_-Dc62fEhuLO45RfiML5k',
    appId: '1:765877075759:android:4002cb064d1acbf42f2bda',
    messagingSenderId: '765877075759',
    projectId: 'personal-ee05e',
    databaseURL: 'https://personal-ee05e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'personal-ee05e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhl245bghyvobwCWq-RNzUBNldwwMw3iM',
    appId: '1:765877075759:ios:df580b446def8d482f2bda',
    messagingSenderId: '765877075759',
    projectId: 'personal-ee05e',
    databaseURL: 'https://personal-ee05e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'personal-ee05e.appspot.com',
    iosBundleId: 'com.example.uptodo',
  );
}
